repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: Cargo\.lock$
    -   id: check-yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus, '--application-directories=.:support']
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.7.0
    hooks:
    -   id: eslint
        args: [--fix]
-   repo: local
    hooks:
    -   id: rubocop
        name: rubocop
        entry: rubocop --auto-correct
        types: [ruby]
        language: ruby
        additional_dependencies: ['rubocop:0.52.0']
