repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: Cargo\.lock$
    -   id: check-yaml
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus, '--application-directories=.:support']
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.14.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        exclude: \.py0\.
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        exclude: \.py0\.
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.25.0
    hooks:
    -   id: eslint
        args: [--fix]
-   repo: local
    hooks:
    -   id: rubocop
        name: rubocop
        entry: rubocop --auto-correct
        types: [ruby]
        language: ruby
        additional_dependencies: ['rubocop:0.52.0']
    -   id: gofmt
        name: gofmt
        language: system
        entry: gofmt -l -w
        files: \.go$
